#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="0.0.3"

ARCHE_STATE_DIR="$HOME/.arche"
CURSOR_DIR="$HOME/.cursor"
CLAUDE_DIR="$HOME/.claude"
ROO_DIR="$HOME/.roo"
KILO_DIR="$HOME/.kilo"
AIDER_GLOBAL_CONF="$HOME/.aider.conf.yml"
CODEX_DIR="$HOME/.codex"
GEMINI_DIR="$HOME/.gemini"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERR]${NC} $*" >&2; }
info() { echo -e "${BLUE}[INFO]${NC} $*"; }

# ==================== Helpers ====================

copy_dir() {
    local src="$1" dst="$2" label="$3"
    if [ -L "$dst" ]; then
        info "Removing old symlink: $dst"
        rm "$dst"
    fi
    mkdir -p "$dst"
    cp -r "$src"/* "$dst"/ 2>/dev/null || true
    log "Copied $label → $dst"
}

clean_dir() {
    local dst="$1" label="$2"
    if [ -L "$dst" ]; then
        rm "$dst"
        info "Removed symlink: $dst ($label)"
    elif [ -d "$dst" ]; then
        rm -rf "$dst"
        info "Removed directory: $dst ($label)"
    fi
}

link_dir() {
    local src="$1" dst="$2" label="$3"
    if [ -L "$dst" ]; then
        rm "$dst"
    elif [ -d "$dst" ]; then
        warn "$dst exists as directory. Backing up to ${dst}.bak"
        mv "$dst" "${dst}.bak"
    fi
    ln -sfn "$src" "$dst"
    log "Linked $label → $dst"
}

# Ensure workspace-local real directory (for workspace-specific knowledge).
# If dst is a symlink (legacy setup), remove it — workspace-specific knowledge
# must NOT flow to global. Preserve existing directory contents.
ensure_local_dir() {
    local dst="$1" label="$2"
    if [ -L "$dst" ]; then
        rm "$dst"
        info "Removed legacy symlink: $dst (converting to workspace-local real directory)"
    fi
    if [ ! -d "$dst" ]; then
        mkdir -p "$dst"
        log "Created workspace-local $label → $dst"
    else
        info "$label already exists as directory: $dst (preserved)"
    fi
}

is_workspace() {
    [ "$(pwd)" != "$HOME" ] && [ "$(pwd)" != "$REPO_DIR" ]
}

has_global() {
    local dir="$1"
    [ -d "$dir/agents" ] || [ -d "$dir/rules" ]
}

generate_agents_md_content() {
    cat << AGENTS_EOF
# AGENTS.md

> Auto-generated by arche framework. Source: $REPO_DIR/

## Framework

This project operates under the **Arche** framework.

## Agent Roles

Available roles (see $REPO_DIR/agents/ for full definitions):

| Role | Layer | Responsibility |
|------|-------|---------------|
| Governance Council (13 seats) | L0 Global | Constitutional oversight, audits, framework governance |
| Archon | L1 Archontes | Coordination, dispatch, strategic partnership |
| Paredros | L1 Archontes | Real-time dispatch monitoring, strategic mirror |
| Polemarch | L1 Archontes | Technical authority, architecture, quality |
| Demiourgos | L1 Archontes | Product vision, UX, branding |
| Symboulos | L1 Archontes | Strategic counsel, advisory |
| Tamias | L1 Archontes | Resource stewardship, cost governance |
| Phylax | L1 Archontes | Security posture, vulnerability oversight |
| Thesmothete | L1 Archontes | Regulation compliance, process quality |
| Strategos | L2 Strategoi | Engineering process, 1st review |
| Epistates | L2 Strategoi | Program coordination, scheduling |
| Grammateus | L3 Hegemones | Project management, planning |
| Taxiarch | L3 Hegemones | Technical execution leadership |
| Mnemon | L3 Hegemones | Knowledge maintenance, ACE loop |
| Skopos | L3 Hegemones | Information gap detection, monitoring |
| Technites | L4 Technitai | Code implementation |

## Rules

### Session Start (MANDATORY)
1. Read **global governance state**: \`\$HOME/.arche/governance.md\`
2. Read **workspace state**: \`state.md\` (if it exists in the project root)

### Constitutional Law
- **Before work**: Search both knowledge destinations for existing articles on the topic
  - Global (universal): tool-level knowledge dir symlinked to \`\$HOME/.arche/knowledge/\`
  - Workspace-local (project-specific): \`<workspace>/.claude/knowledge/\` (and tool equivalents under \`.cursor/\`, \`.roo/\`, \`.kilo/\`)
- **After work** (per Law Article 5.2):
  - Transferable finding → global knowledge
  - Project-specific finding → workspace-local knowledge
  - Follow Regulation 5 format (Title, Context, Reasoning Chain, Alternatives, Key Findings, Evidence, Falsifiable Predictions, Corrections Log)
- Communication: Agent artifacts in English; user-facing in user's language
- Model allocation: Strongest for strategy/review, fastest for execution

### Quality Standards
- 0 warnings, 0 errors on every build
- No warning suppression (<NoWarn> forbidden)
- Fix warnings in source code

## Knowledge Base

Knowledge is stored in two locations (Law Article 1):
- **Universal** (applies to any codebase): \`\$HOME/.arche/knowledge/\` (global)
- **Workspace-specific** (project-local): \`<workspace>/.claude/knowledge/\` and equivalents under other tools' dirs — real directories, not shared with other workspaces

Obligations:
- **Before work**: Search BOTH locations for existing articles
- **After work**: Pick destination per Article 5.2; write per Regulation 5 format
- **Promotion**: Mnemon proposes workspace-local → global → repo seed per Article 8
AGENTS_EOF
}

# ==================== Clean Functions ====================

clean_cursor() {
    info "Cleaning Cursor config..."
    clean_dir "$CURSOR_DIR/agents" "agents"
    clean_dir "$CURSOR_DIR/knowledge" "knowledge"
    clean_dir "$CURSOR_DIR/rules" "rules"
    [ -L "$CURSOR_DIR/governance-state.md" ] && rm "$CURSOR_DIR/governance-state.md"
    [ -L "$CURSOR_DIR/governance.md" ] && rm "$CURSOR_DIR/governance.md"
    log "Cursor config cleaned"
}

clean_claude() {
    info "Cleaning Claude Code config..."
    clean_dir "$CLAUDE_DIR/agents" "agents"
    clean_dir "$CLAUDE_DIR/knowledge" "knowledge"
    clean_dir "$CLAUDE_DIR/rules" "rules"
    [ -L "$CLAUDE_DIR/governance-state.md" ] && rm "$CLAUDE_DIR/governance-state.md"
    [ -L "$CLAUDE_DIR/governance.md" ] && rm "$CLAUDE_DIR/governance.md"
    [ -f "$CLAUDE_DIR/CLAUDE.md" ] && rm "$CLAUDE_DIR/CLAUDE.md"
    log "Claude Code config cleaned"
}

clean_roo() {
    info "Cleaning Roo Code config..."
    clean_dir "$ROO_DIR/rules" "rules"
    clean_dir "$ROO_DIR/knowledge" "knowledge"
    [ -L "$ROO_DIR/governance-state.md" ] && rm "$ROO_DIR/governance-state.md"
    [ -L "$ROO_DIR/governance.md" ] && rm "$ROO_DIR/governance.md"
    log "Roo Code config cleaned"
}

clean_kilo() {
    info "Cleaning Kilo Code config..."
    clean_dir "$KILO_DIR/rules" "rules"
    clean_dir "$KILO_DIR/knowledge" "knowledge"
    [ -L "$KILO_DIR/governance-state.md" ] && rm "$KILO_DIR/governance-state.md"
    [ -L "$KILO_DIR/governance.md" ] && rm "$KILO_DIR/governance.md"
    log "Kilo Code config cleaned"
}

clean_aider() {
    info "Cleaning Aider config..."
    [ -d "$HOME/.aider" ] && rm -rf "$HOME/.aider" && info "Removed ~/.aider/"
    [ -f "$AIDER_GLOBAL_CONF" ] && rm "$AIDER_GLOBAL_CONF" && info "Removed ~/.aider.conf.yml"
    log "Aider config cleaned"
}

ensure_state_md() {
    if is_workspace && [ ! -f "./state.md" ]; then
        cp "$REPO_DIR/state.md.template" "./state.md"
        log "Created state.md from template"
    fi
}

ensure_governance_state() {
    mkdir -p "$ARCHE_STATE_DIR"
    if [ ! -f "$ARCHE_STATE_DIR/governance.md" ]; then
        cp "$REPO_DIR/governance.md" "$ARCHE_STATE_DIR/governance.md"
        log "Created ~/.arche/governance.md from initial state"
    else
        info "~/.arche/governance.md already exists, preserving"
    fi
}

ensure_knowledge() {
    local dst="$ARCHE_STATE_DIR/knowledge"
    if [ ! -d "$dst" ]; then
        cp -r "$REPO_DIR/knowledge" "$dst"
        log "Seeded ~/.arche/knowledge/ from repo"
    else
        info "~/.arche/knowledge/ already exists, preserving"
    fi
}

register_workspace() {
    local ws="$1"
    local registry="$ARCHE_STATE_DIR/workspaces.list"
    mkdir -p "$ARCHE_STATE_DIR"
    touch "$registry"
    if ! grep -Fxq "$ws" "$registry" 2>/dev/null; then
        echo "$ws" >> "$registry"
        info "Registered workspace → $registry"
    fi
}

list_workspaces() {
    local registry="$ARCHE_STATE_DIR/workspaces.list"
    [ -f "$registry" ] || return 0
    grep -v '^[[:space:]]*$' "$registry" 2>/dev/null || true
}

cmd_sync_all() {
    local registry="$ARCHE_STATE_DIR/workspaces.list"
    info "Syncing all registered workspaces..."

    info "→ Global sync first (cursor, claude, roo, kilo)"
    for t in cursor claude roo kilo; do
        cmd_update "$t" 2>/dev/null || warn "$t global update skipped (not installed)"
    done

    if [ ! -f "$registry" ]; then
        warn "No workspace registry at $registry — nothing to sync"
        return 0
    fi

    local count=0 missing=0 failed=0
    while IFS= read -r ws; do
        [ -z "$ws" ] && continue
        count=$((count + 1))
        if [ ! -d "$ws" ]; then
            warn "Workspace missing, skipping: $ws"
            missing=$((missing + 1))
            continue
        fi
        info "→ Syncing workspace: $ws"
        (
            cd "$ws" || exit 1
            # Claude workspace setup (symlink migration for .claude/)
            if [ -d "./.claude" ]; then
                setup_claude_smart
            fi
            # Cursor workspace setup (.mdc conversion)
            if [ -d "./.cursor" ]; then
                setup_cursor_smart
            fi
            # Roo / Kilo workspace setup
            if [ -d "./.roo" ]; then
                setup_roo_smart
            fi
            if [ -d "./.kilo" ]; then
                setup_kilo_smart
            fi
            # Generic workspace tools (AGENTS.md, Gemini, Cline, Copilot, Windsurf, Aider)
            setup_workspace
        ) || {
            err "Workspace sync failed: $ws"
            failed=$((failed + 1))
        }
    done < "$registry"

    echo ""
    log "sync-all summary: $count registered, $missing missing, $failed failed"
}

cmd_doctor() {
    info "Checking Arche symlink health..."
    local issues=0

    local check_paths=(
        "$HOME/.cursor/knowledge"
        "$HOME/.cursor/governance.md"
        "$HOME/.claude/agents"
        "$HOME/.claude/rules"
        "$HOME/.claude/knowledge"
        "$HOME/.claude/governance.md"
        "$HOME/.roo/knowledge"
        "$HOME/.kilo/knowledge"
    )

    for p in "${check_paths[@]}"; do
        if [ -L "$p" ]; then
            if [ -e "$p" ]; then
                local target
                target=$(readlink "$p")
                log "OK symlink: $p → $target"
            else
                err "BROKEN symlink: $p → $(readlink "$p")"
                issues=$((issues + 1))
            fi
        elif [ -e "$p" ]; then
            warn "NOT symlink (copy/dir): $p — consider 'arche sync-all' to migrate"
        else
            info "MISSING: $p (tool not installed)"
        fi
    done

    echo ""
    local registry="$ARCHE_STATE_DIR/workspaces.list"
    if [ -f "$registry" ]; then
        info "Checking registered workspaces..."
        while IFS= read -r ws; do
            [ -z "$ws" ] && continue
            if [ ! -d "$ws" ]; then
                warn "Registered workspace missing: $ws"
                issues=$((issues + 1))
                continue
            fi
            for sub in agents rules governance.md; do
                local p="$ws/.claude/$sub"
                [ -e "$p" ] || continue
                if [ -L "$p" ]; then
                    if [ -e "$p" ]; then
                        log "OK workspace link: $p"
                    else
                        err "BROKEN workspace symlink: $p"
                        issues=$((issues + 1))
                    fi
                else
                    warn "NOT symlink: $p — run 'cd $ws && arche claude'"
                fi
            done

            # workspace-local knowledge dirs (MUST be real directories, never symlinks).
            # A symlink here means legacy setup where workspace knowledge drained into global.
            for tool_dir in .claude .cursor .roo .kilo; do
                local kp="$ws/$tool_dir/knowledge"
                [ -e "$kp" ] || continue
                if [ -L "$kp" ]; then
                    err "LEGACY symlink (workspace knowledge must be real dir): $kp — run 'cd $ws && arche claude' to migrate"
                    issues=$((issues + 1))
                elif [ -d "$kp" ]; then
                    log "OK workspace-local knowledge dir: $kp"
                else
                    warn "NOT a directory: $kp"
                    issues=$((issues + 1))
                fi
            done
        done < "$registry"
    else
        info "No workspace registry yet (normal for fresh install)"
    fi

    echo ""
    if [ "$issues" -eq 0 ]; then
        log "Doctor: no issues detected"
    else
        err "Doctor: $issues issue(s) detected"
        return 1
    fi
}

# ==================== Cursor ====================

setup_cursor_global() {
    info "Setting up Cursor IDE → $CURSOR_DIR"
    ensure_governance_state
    ensure_knowledge
    mkdir -p "$CURSOR_DIR"

    copy_dir "$REPO_DIR/agents" "$CURSOR_DIR/agents" "agents"

    link_dir "$ARCHE_STATE_DIR/knowledge" "$CURSOR_DIR/knowledge" "knowledge"
    ln -sfn "$ARCHE_STATE_DIR/governance.md" "$CURSOR_DIR/governance.md"

    mkdir -p "$CURSOR_DIR/rules"
    for rule in "$REPO_DIR"/rules/*.md; do
        [ -f "$rule" ] || continue
        local base
        base="$(basename "$rule" .md)"
        cp "$rule" "$CURSOR_DIR/rules/${base}.mdc"
    done
    log "Copied rules (.md → .mdc) → $CURSOR_DIR/rules/"

    log "Cursor global setup complete"
}

setup_cursor_workspace() {
    info "Setting up Cursor workspace → .cursor/"

    copy_dir "$REPO_DIR/agents" ".cursor/agents" "agents"

    mkdir -p ".cursor/rules"
    for rule in "$REPO_DIR"/rules/*.md; do
        [ -f "$rule" ] || continue
        local base
        base="$(basename "$rule" .md)"
        cp "$rule" ".cursor/rules/${base}.mdc"
    done
    log "Copied rules (.md → .mdc) → .cursor/rules/"

    ensure_local_dir ".cursor/knowledge" "knowledge (workspace-local)"

    info "NOTE: .cursor/rules/*.mdc from arche are generic. Add project-specific rules separately."
    log "Cursor workspace setup complete"
}

setup_cursor_smart() {
    if is_workspace; then
        ensure_state_md
        if ! has_global "$CURSOR_DIR"; then
            setup_cursor_global
            echo ""
        fi
        setup_cursor_workspace
    else
        setup_cursor_global
    fi
}

# ==================== Claude Code ====================

setup_claude_global() {
    info "Setting up Claude Code → $CLAUDE_DIR"
    ensure_governance_state
    ensure_knowledge
    mkdir -p "$CLAUDE_DIR"

    link_dir "$REPO_DIR/agents" "$CLAUDE_DIR/agents" "agents"

    link_dir "$ARCHE_STATE_DIR/knowledge" "$CLAUDE_DIR/knowledge" "knowledge"
    rm -f "$CLAUDE_DIR/governance.md"
    ln -sfn "$ARCHE_STATE_DIR/governance.md" "$CLAUDE_DIR/governance.md"
    log "Linked governance.md → $CLAUDE_DIR/governance.md"

    link_dir "$REPO_DIR/rules" "$CLAUDE_DIR/rules" "rules"

    cat > "$CLAUDE_DIR/CLAUDE.md" << 'CLAUDE_GLOBAL_EOF'
# Arche Framework

IMPORTANT: YOU MUST COMPLETE SESSION INITIALIZATION BEFORE ANY OTHER ACTION.

## Session Start — MANDATORY (Do this FIRST, before ANY response)

STOP. Before you respond to ANY user request, you MUST complete these steps:

1. Read `$HOME/.arche/governance.md` — check authorization status and expiry
2. Read `state.md` in the project root (if it exists) — check Standing, cycle counters, unaudited cycles
3. Output a **Governance Report** as your FIRST response:

```
Governance Report:
- Authorization: [Authorized/Degraded] (expires: [date])
- Archon Standing: [Authorized/Probation/Suspended]
- Cycle Count: [N]
- Unaudited Cycles: [list or none]
- Pending Triggers: [list or none]
- Active Role: [detected role]
```

4. If authorization is expired or Degraded: notify the user and await direction
5. If any role is in Probation/Suspended: state recovery conditions

**Failure to complete this initialization means ALL work in this session will be recorded as UNAUDITED and governance violations will accumulate.**

DO NOT skip this to "save time" or "be helpful." The Founder expects governance compliance FIRST.

## Structure

- **Agents**: `~/.claude/agents/` — role definitions
- **Rules**: `~/.claude/rules/` — law.md + regulation.md
- **Knowledge (universal)**: `~/.claude/knowledge/` — symlink to `~/.arche/knowledge/` (universal knowledge, shared across all Arche workspaces)
- **Governance**: `~/.arche/governance.md` — global governance state

Workspace-specific knowledge lives inside each workspace at `<workspace>/.claude/knowledge/` (real directory, not shared).

## Quick Reference

- **Role activation**: Read `~/.claude/agents/<role>.md`
- **Before work**: Search `~/.claude/knowledge/` for universal articles AND `<workspace>/.claude/knowledge/` for project-specific articles
- **After work** (per Law Article 5.2):
  - Transferable finding → `~/.claude/knowledge/` (global/universal)
  - Project-specific finding → `<workspace>/.claude/knowledge/` (workspace-local)
  - Ambiguous → workspace-local; Mnemon evaluates for promotion per Article 8
- **Model allocation**: Strongest for strategy/review, fastest for execution

## Workspace Integration

Project-specific extensions: `<workspace>/.claude/{agents,rules,knowledge,hooks}`
- `agents`, `rules`: symlinks to global framework
- `knowledge`: **real directory** holding workspace-specific articles (not shared)
- Project overview: `<workspace>/CLAUDE.md`
CLAUDE_GLOBAL_EOF
    log "Generated CLAUDE.md"

    if [ -d "$REPO_DIR/mcp-server/src" ]; then
        info "Building MCP server..."
        if [ ! -d "$REPO_DIR/mcp-server/node_modules" ]; then
            (cd "$REPO_DIR/mcp-server" && npm install --silent 2>/dev/null) || warn "npm install failed"
        fi
        (cd "$REPO_DIR/mcp-server" && npm run build --silent 2>/dev/null) || warn "MCP build failed"

        if command -v claude &> /dev/null; then
            claude mcp add --scope user --transport stdio arche-knowledge -- node "$REPO_DIR/mcp-server/dist/index.js" 2>/dev/null || true
            log "MCP server registered"
        else
            warn "'claude' CLI not found. Register MCP manually:"
            echo "  claude mcp add --scope user --transport stdio arche-knowledge -- node $REPO_DIR/mcp-server/dist/index.js"
        fi
    fi

    info "NOTE: ~/.claude/settings.json not modified (preserving user config)"
    log "Claude Code global setup complete"
}

setup_claude_workspace() {
    info "Setting up Claude Code workspace → .claude/"

    link_dir "$REPO_DIR/agents" ".claude/agents" "agents"

    link_dir "$REPO_DIR/rules" ".claude/rules" "rules"

    if [ -d "$REPO_DIR/hooks" ] && [ "$(ls -A "$REPO_DIR/hooks" 2>/dev/null)" ]; then
        link_dir "$REPO_DIR/hooks" ".claude/hooks" "hooks"
    fi

    ensure_local_dir ".claude/knowledge" "knowledge (workspace-local)"
    rm -f ".claude/governance.md"
    ln -sfn "$ARCHE_STATE_DIR/governance.md" ".claude/governance.md"
    log "Linked governance.md → .claude/governance.md"

    register_workspace "$(pwd)"

    cat > "./CLAUDE.md" << 'CLAUDE_WORKSPACE_EOF'
# Project — Arche Framework

IMPORTANT: YOU MUST COMPLETE SESSION INITIALIZATION BEFORE ANY OTHER ACTION.

## Session Start — MANDATORY (Do this FIRST, before ANY response)

STOP. Before you respond to ANY user request, you MUST complete these steps:

1. Read `$HOME/.arche/governance.md` — check authorization status and expiry
2. Read `state.md` in the project root — check Standing, cycle counters, unaudited cycles
3. Output a **Governance Report** as your FIRST response:

```
Governance Report:
- Authorization: [Authorized/Degraded] (expires: [date])
- Archon Standing: [Authorized/Probation/Suspended]
- Cycle Count: [N]
- Unaudited Cycles: [list or none]
- Pending Triggers: [list or none]
- Active Role: [detected role]
```

4. If authorization is expired or Degraded: notify the user and await direction
5. If any role is in Probation/Suspended: state recovery conditions

**Failure to complete this initialization means ALL work in this session will be recorded as UNAUDITED and governance violations will accumulate.**

DO NOT skip this to "save time" or "be helpful." The Founder expects governance compliance FIRST.
Proceed with work ONLY after Governance Report has been output.

## Structure

- **Agents**: `.claude/agents/` — role definitions (symlinked to `$HOME/arche/agents/`)
- **Rules**: `.claude/rules/` — coding standards and regulations (symlinked to `$HOME/arche/rules/`)
- **Knowledge (workspace-local)**: `.claude/knowledge/` — project-specific knowledge (real directory, not shared with other workspaces)
- **Knowledge (global, universal)**: `$HOME/.arche/knowledge/` — universal knowledge shared across all Arche workspaces (read-only from this workspace's perspective)
- **Hooks**: `.claude/hooks/` — automation hooks

## Quality Standards

- 0 warnings, 0 errors on every build
- No warning suppression — fix in source code
- Clean build before verification

## Knowledge Obligations

Per Law Article 5:

- **Before work (read)**:
  - Search `$HOME/.arche/knowledge/` for universal articles
  - Search `.claude/knowledge/` for workspace-specific articles
- **After work (write)**:
  - Transferable finding (applies to any codebase) → `$HOME/.arche/knowledge/` (global)
  - Project-specific finding → `.claude/knowledge/` (workspace-local; stays in this workspace)
  - Ambiguous → default to workspace-local; Mnemon evaluates for promotion per Article 8
- Follow Regulation 5 format (Title, Context, Reasoning Chain, Alternatives, Key Findings, Evidence, Falsifiable Predictions, Corrections Log)

## Communication

- Agent artifacts: English
- User-facing: User's preferred language
CLAUDE_WORKSPACE_EOF
    log "Generated ./CLAUDE.md"

    info "NOTE: .claude/settings.json not modified (preserving user config)"
    log "Claude Code workspace setup complete"
}

setup_claude_smart() {
    if is_workspace; then
        ensure_state_md
        if ! has_global "$CLAUDE_DIR"; then
            setup_claude_global
            echo ""
        fi
        setup_claude_workspace
    else
        setup_claude_global
    fi
}

# ==================== Roo Code ====================

setup_roo_global() {
    info "Setting up Roo Code → $ROO_DIR"
    ensure_governance_state
    ensure_knowledge
    mkdir -p "$ROO_DIR/rules"

    for agent in "$REPO_DIR"/agents/*.md; do
        [ -f "$agent" ] || continue
        local base
        base="$(basename "$agent")"
        cp "$agent" "$ROO_DIR/rules/agent-${base}"
    done
    log "Copied agent definitions as rules → $ROO_DIR/rules/"

    for rule in "$REPO_DIR"/rules/*.md; do
        [ -f "$rule" ] || continue
        cp "$rule" "$ROO_DIR/rules/$(basename "$rule")"
    done
    log "Copied rules → $ROO_DIR/rules/"

    link_dir "$ARCHE_STATE_DIR/knowledge" "$ROO_DIR/knowledge" "knowledge"
    ln -sfn "$ARCHE_STATE_DIR/governance.md" "$ROO_DIR/governance.md"

    log "Roo Code global setup complete"
}

setup_roo_workspace() {
    info "Setting up Roo Code workspace → .roo/"
    mkdir -p ".roo/rules"

    for agent in "$REPO_DIR"/agents/*.md; do
        [ -f "$agent" ] || continue
        local base
        base="$(basename "$agent")"
        cp "$agent" ".roo/rules/agent-${base}"
    done
    log "Copied agent definitions as rules → .roo/rules/"

    for rule in "$REPO_DIR"/rules/*.md; do
        [ -f "$rule" ] || continue
        cp "$rule" ".roo/rules/$(basename "$rule")"
    done
    log "Copied rules → .roo/rules/"

    ensure_local_dir ".roo/knowledge" "knowledge (workspace-local)"

    log "Roo Code workspace setup complete"
}

setup_roo_smart() {
    if is_workspace; then
        ensure_state_md
        if ! has_global "$ROO_DIR"; then
            setup_roo_global
            echo ""
        fi
        setup_roo_workspace
    else
        setup_roo_global
    fi
}

# ==================== Kilo Code ====================

setup_kilo_global() {
    info "Setting up Kilo Code → $KILO_DIR"
    ensure_governance_state
    ensure_knowledge
    mkdir -p "$KILO_DIR/rules"

    for agent in "$REPO_DIR"/agents/*.md; do
        [ -f "$agent" ] || continue
        local base
        base="$(basename "$agent")"
        cp "$agent" "$KILO_DIR/rules/agent-${base}"
    done
    log "Copied agent definitions as rules → $KILO_DIR/rules/"

    for rule in "$REPO_DIR"/rules/*.md; do
        [ -f "$rule" ] || continue
        cp "$rule" "$KILO_DIR/rules/$(basename "$rule")"
    done
    log "Copied rules → $KILO_DIR/rules/"

    link_dir "$ARCHE_STATE_DIR/knowledge" "$KILO_DIR/knowledge" "knowledge"
    ln -sfn "$ARCHE_STATE_DIR/governance.md" "$KILO_DIR/governance.md"

    log "Kilo Code global setup complete"
}

setup_kilo_workspace() {
    info "Setting up Kilo Code workspace → .kilo/"
    mkdir -p ".kilo/rules"

    for agent in "$REPO_DIR"/agents/*.md; do
        [ -f "$agent" ] || continue
        local base
        base="$(basename "$agent")"
        cp "$agent" ".kilo/rules/agent-${base}"
    done
    log "Copied agent definitions as rules → .kilo/rules/"

    for rule in "$REPO_DIR"/rules/*.md; do
        [ -f "$rule" ] || continue
        cp "$rule" ".kilo/rules/$(basename "$rule")"
    done
    log "Copied rules → .kilo/rules/"

    ensure_local_dir ".kilo/knowledge" "knowledge (workspace-local)"

    log "Kilo Code workspace setup complete"
}

setup_kilo_smart() {
    if is_workspace; then
        ensure_state_md
        if ! has_global "$KILO_DIR"; then
            setup_kilo_global
            echo ""
        fi
        setup_kilo_workspace
    else
        setup_kilo_global
    fi
}

# ==================== Aider ====================

setup_aider_global() {
    info "Setting up Aider (global) → ~/.aider.conf.yml"

    local aider_dir="$HOME/.aider"
    mkdir -p "$aider_dir"

    cat > "$aider_dir/CONVENTIONS.md" << CONV_EOF
# Coding Conventions (Arche)

> Auto-generated by arche framework. Source: $REPO_DIR/

## Agent Roles
When operating in a specific role, read the definition from $REPO_DIR/agents/<role>.md.
Available: archon, polemarch, demiourgos, symboulos, tamias, phylax, thesmothete, strategos, epistates, grammateus, taxiarch, mnemon, skopos, technites, constitution, regulation, process, quality, architecture, security, knowledge, ethics, performance, continuity, evolution, coherence, diabolos.

## Constitutional Law
### Session Start (MANDATORY)
1. Read **global governance state**: \`\$HOME/.arche/governance.md\`
2. Read **workspace state**: \`state.md\` (if it exists in the project root)

### Rules
- **Before work**: Search ~/.arche/knowledge/ for existing knowledge on the topic
- **After work**: Write transferable findings to ~/.arche/knowledge/ per Regulation 5 format
- Communication: Agent artifacts in English; user-facing in user's language
- Model allocation: Strongest for strategy/review, fastest for execution

## Quality Standards
- 0 warnings, 0 errors on every build
- No warning suppression — fix in source code
- Clean build before verification

## Workflow
- Deploy and verify after changes
- Knowledge articles must include reasoning chains, not just conclusions
CONV_EOF
    log "Generated ~/.aider/CONVENTIONS.md"

    if [ -f "$AIDER_GLOBAL_CONF" ]; then
        if grep -q 'CONVENTIONS.md' "$AIDER_GLOBAL_CONF" 2>/dev/null; then
            log "~/.aider.conf.yml already references CONVENTIONS.md"
        else
            warn "~/.aider.conf.yml exists but doesn't reference CONVENTIONS.md"
            echo "  Add this to ~/.aider.conf.yml:"
            echo "  read: [$aider_dir/CONVENTIONS.md]"
        fi
    else
        cat > "$AIDER_GLOBAL_CONF" << EOF
# Arche Aider global configuration
read:
  - $aider_dir/CONVENTIONS.md
EOF
        log "Generated ~/.aider.conf.yml"
    fi

    log "Aider global setup complete"
}

setup_aider_workspace() {
    info "Generating Aider workspace config"
    if [ -f "$HOME/.aider/CONVENTIONS.md" ]; then
        cp "$HOME/.aider/CONVENTIONS.md" "./CONVENTIONS.md"
    else
        cat > "./CONVENTIONS.md" << 'CONV_EOF'
# Coding Conventions (Arche)
## Quality Standards
- 0 warnings, 0 errors on every build
- No warning suppression — fix in source
CONV_EOF
    fi
    log "Generated ./CONVENTIONS.md"

    if [ ! -f ".aider.conf.yml" ]; then
        cat > ".aider.conf.yml" << 'AIDER_EOF'
read:
  - CONVENTIONS.md
AIDER_EOF
        log "Generated ./.aider.conf.yml"
    else
        warn ".aider.conf.yml already exists — not overwriting"
    fi
}

setup_aider_smart() {
    if is_workspace; then
        ensure_state_md
        if [ ! -f "$AIDER_GLOBAL_CONF" ]; then
            setup_aider_global
            echo ""
        fi
        setup_aider_workspace
    else
        setup_aider_global
    fi
}

# ==================== Workspace-Only Tools ====================

setup_codex_workspace() {
    info "Generating AGENTS.md (Codex CLI / AGENTS.md standard)"
    generate_agents_md_content > "./AGENTS.md"
    log "Generated ./AGENTS.md"
}

setup_codex_smart() {
    if is_workspace; then
        ensure_state_md
        setup_codex_workspace
    else
        warn "Codex is workspace-only. Run from a project directory."
    fi
}

setup_gemini_workspace() {
    info "Generating Gemini CLI configuration"

    generate_agents_md_content | sed 's/^# AGENTS.md/# GEMINI.md/' > "./GEMINI.md"
    log "Generated ./GEMINI.md"

    mkdir -p ".gemini"
    cat > ".gemini/settings.json" << 'EOF'
{
  "context": {
    "fileName": "GEMINI.md"
  }
}
EOF
    log "Generated .gemini/settings.json"
}

setup_gemini_smart() {
    if is_workspace; then
        ensure_state_md
        setup_gemini_workspace
    else
        warn "Gemini is workspace-only. Run from a project directory."
    fi
}

setup_cline_workspace() {
    info "Generating Cline configuration"
    generate_agents_md_content | sed 's/^# AGENTS.md/# Cline Rules (Arche)/' > "./.clinerules"
    log "Generated ./.clinerules"
}

setup_cline_smart() {
    if is_workspace; then
        ensure_state_md
        setup_cline_workspace
    else
        warn "Cline is workspace-only. Run from a project directory."
    fi
}

setup_copilot_workspace() {
    info "Generating GitHub Copilot configuration"
    mkdir -p ".github"
    generate_agents_md_content | sed 's/^# AGENTS.md/# Copilot Instructions (Arche)/' > ".github/copilot-instructions.md"
    log "Generated .github/copilot-instructions.md"

    if [ ! -f "./AGENTS.md" ]; then
        generate_agents_md_content > "./AGENTS.md"
        log "Generated ./AGENTS.md (Copilot also reads this)"
    fi
}

setup_copilot_smart() {
    if is_workspace; then
        ensure_state_md
        setup_copilot_workspace
    else
        warn "Copilot is workspace-only. Run from a project directory."
    fi
}

setup_windsurf_workspace() {
    info "Generating Windsurf configuration"
    generate_agents_md_content | sed 's/^# AGENTS.md/# Windsurf Rules (Arche)/' > "./.windsurfrules"
    log "Generated ./.windsurfrules"
}

setup_windsurf_smart() {
    if is_workspace; then
        ensure_state_md
        setup_windsurf_workspace
    else
        warn "Windsurf is workspace-only. Run from a project directory."
    fi
}

setup_agents_md_workspace() {
    setup_codex_workspace
}

setup_agents_md_smart() {
    if is_workspace; then
        ensure_state_md
        setup_agents_md_workspace
    else
        warn "agents-md is workspace-only. Run from a project directory."
    fi
}

# ==================== Commands ====================

setup_all() {
    echo ""
    echo "Arche Framework Setup v${VERSION}"
    echo "=================================="
    echo "Source: $REPO_DIR"
    echo ""

    setup_cursor_smart
    echo ""
    setup_claude_smart
    echo ""
    setup_roo_smart
    echo ""
    setup_kilo_smart
    echo ""
    setup_aider_smart

    if is_workspace; then
        echo ""
        setup_codex_smart
        echo ""
        setup_gemini_smart
        echo ""
        setup_cline_smart
        echo ""
        setup_copilot_smart
        echo ""
        setup_windsurf_smart
    fi
}

setup_workspace() {
    if ! is_workspace; then
        err "workspace target must be run from a project directory (not ~/ or the arche repo)"
        exit 1
    fi

    if [ ! -f "./state.md" ]; then
        cp "$REPO_DIR/state.md.template" "./state.md"
        log "Created state.md from template"
    else
        info "state.md already exists, skipping"
    fi

    echo ""
    echo "Arche Workspace Setup v${VERSION}"
    echo "=================================="
    echo "Target: $(pwd)"
    echo ""

    setup_codex_smart
    echo ""
    setup_gemini_smart
    echo ""
    setup_cline_smart
    echo ""
    setup_copilot_smart
    echo ""
    setup_windsurf_smart
    echo ""
    setup_aider_smart
    echo ""
    setup_agents_md_smart
}

_check_global() {
    local name="$1" dir="$2"
    if [ -d "$dir/agents" ] || [ -d "$dir/rules" ]; then
        echo -e "  ${GREEN}✓${NC} $name ($dir)"
        [ -d "$dir/agents" ] && echo "    agents: $(ls "$dir/agents/" 2>/dev/null | wc -l) files"
        [ -d "$dir/rules" ] && echo "    rules:  $(ls "$dir/rules/" 2>/dev/null | wc -l) files"
        if [ -L "$dir/knowledge" ]; then
            echo "    knowledge: linked → $(readlink "$dir/knowledge")"
        elif [ -d "$dir/knowledge" ]; then
            echo "    knowledge: directory ($(find "$dir/knowledge" -name '*.md' 2>/dev/null | wc -l) articles)"
        else
            echo "    knowledge: not installed"
        fi
    else
        echo -e "  ${RED}✗${NC} $name — not installed"
    fi
}

cmd_status() {
    echo "Arche Framework Status v${VERSION}"
    echo "===================================="
    echo "Source: $REPO_DIR"
    echo ""

    echo "Global installations:"
    _check_global "Cursor" "$CURSOR_DIR"
    _check_global "Claude Code" "$CLAUDE_DIR"
    _check_global "Roo Code" "$ROO_DIR"
    _check_global "Kilo Code" "$KILO_DIR"

    if [ -f "$AIDER_GLOBAL_CONF" ]; then
        echo -e "  ${GREEN}✓${NC} Aider (~/.aider.conf.yml)"
        [ -f "$HOME/.aider/CONVENTIONS.md" ] && echo "    conventions: present" || echo "    conventions: missing"
    else
        echo -e "  ${RED}✗${NC} Aider — not installed"
    fi

    echo ""
    echo "Workspace files (current directory: $(pwd)):"
    for f in AGENTS.md GEMINI.md CONVENTIONS.md .clinerules .windsurfrules .github/copilot-instructions.md CLAUDE.md .aider.conf.yml .gemini/settings.json; do
        if [ -f "./$f" ]; then
            echo -e "  ${GREEN}✓${NC} $f"
        else
            echo -e "  ${YELLOW}·${NC} $f — not present"
        fi
    done

    echo ""
    echo "Context: $(pwd)"
    if is_workspace; then
        echo "  Mode: workspace (smart setup will install workspace + global if needed)"
    else
        echo "  Mode: global-only (smart setup will install global config)"
    fi
}

cmd_update() {
    local target="$1"
    info "Updating $target from source..."
    case "$target" in
        cursor)  setup_cursor_global ;;
        claude)  setup_claude_global ;;
        roo)     setup_roo_global ;;
        kilo)    setup_kilo_global ;;
        aider)   setup_aider_global ;;
        knowledge)
            ensure_knowledge
            local added=0
            while IFS= read -r -d '' src; do
                local rel="${src#$REPO_DIR/knowledge/}"
                local dst="$ARCHE_STATE_DIR/knowledge/$rel"
                if [ ! -f "$dst" ]; then
                    mkdir -p "$(dirname "$dst")"
                    cp "$src" "$dst"
                    log "Added new article: $rel"
                    added=$((added + 1))
                fi
            done < <(find "$REPO_DIR/knowledge" -name '*.md' -print0)
            if [ "$added" -eq 0 ]; then
                info "No new articles to add (all seed articles already exist in ~/.arche/knowledge/)"
            else
                log "Added $added new article(s) to ~/.arche/knowledge/"
            fi
            ;;
        *)       err "Update works for: cursor, claude, roo, kilo, aider, knowledge"; exit 1 ;;
    esac
}

cmd_init() {
    local target="$1"
    info "Initializing $target (clean + setup)..."
    case "$target" in
        cursor)  clean_cursor; setup_cursor_smart ;;
        claude)  clean_claude; setup_claude_smart ;;
        roo)     clean_roo;    setup_roo_smart ;;
        kilo)    clean_kilo;   setup_kilo_smart ;;
        aider)   clean_aider;  setup_aider_smart ;;
        all)
            for t in cursor claude roo kilo aider; do
                cmd_init "$t"
                echo ""
            done
            return
            ;;
        *)       err "Init works for: cursor, claude, roo, kilo, aider, all"; exit 1 ;;
    esac
    log "$target initialized"
}

usage() {
    cat << USAGE
Arche Framework Setup v${VERSION}

Usage:
  ./setup.sh <tool> [<tool> ...]    Set up specified tools (auto-detects scope)
  ./setup.sh init <tool|all>        Clean existing config, then set up fresh
  ./setup.sh update <tool>          Re-sync global config from source
  ./setup.sh update knowledge       Merge new seed articles into ~/.arche/knowledge/
  ./setup.sh sync-all               Re-sync global + all registered workspaces (symlink mode)
  ./setup.sh doctor                 Check symlink health across all installations
  ./setup.sh status                 Show installation status
  ./setup.sh -h | --help            Show this help

Tools:
  cursor    Cursor IDE
  claude    Claude Code
  roo       Roo Code
  kilo      Kilo Code
  aider     Aider
  codex     OpenAI Codex CLI     (workspace only)
  gemini    Gemini CLI           (workspace only)
  cline     Cline                (workspace only)
  copilot   GitHub Copilot       (workspace only)
  windsurf  Windsurf             (workspace only)
  agents-md AGENTS.md standard   (workspace only)
  all       All applicable tools
  workspace All workspace-only tools

Behavior:
  From ~/  (or non-project dir) → installs global config only
  From a project directory      → installs workspace config
                                  (+ global if not yet installed)

Strategy:
  agents/ and rules/ are SYMLINKED to source (auto-follow on source edits)
  knowledge/ is SYMLINKED to ~/.arche/knowledge/ (bidirectional, agents write back)
  governance.md is SYMLINKED to ~/.arche/governance.md (global state)
  Cursor rules/ are COPIED with .mdc conversion (Cursor format requirement)

Examples:
  ./setup.sh <tool> [tool...]     # From ~/ → global only
  cd myproject && ~/arche/setup.sh <tool>  # workspace + global if needed
  ./setup.sh all                  # Everything applicable to current context
  ./setup.sh init <tool>          # Clean old files, then fresh install
  ./setup.sh init all             # Clean + fresh install for all global tools
  ./setup.sh update <tool>        # Re-sync global config
  ./setup.sh update knowledge     # Add new seed articles (no overwrite)
  ./setup.sh sync-all             # Re-sync global + all registered workspaces
  ./setup.sh doctor               # Check symlink health
  ./setup.sh status               # Show what's installed
USAGE
}

# ==================== Main ====================

if [ $# -eq 0 ]; then
    usage
    exit 0
fi

case "$1" in
    -h|--help) usage; exit 0 ;;
    status)    cmd_status; exit 0 ;;
    doctor)    cmd_doctor; exit $? ;;
    sync-all)  cmd_sync_all; exit 0 ;;
    update)
        shift
        [ $# -eq 0 ] && { err "Usage: ./setup.sh update <target>"; exit 1; }
        cmd_update "$1"
        exit 0
        ;;
    init)
        shift
        [ $# -eq 0 ] && { err "Usage: ./setup.sh init <target|all>"; exit 1; }
        cmd_init "$1"
        echo -e "${GREEN}Done.${NC}"
        exit 0
        ;;
esac

for target in "$@"; do
    case "$target" in
        cursor)    setup_cursor_smart ;;
        claude)    setup_claude_smart ;;
        roo)       setup_roo_smart ;;
        kilo)      setup_kilo_smart ;;
        aider)     setup_aider_smart ;;
        codex)     setup_codex_smart ;;
        gemini)    setup_gemini_smart ;;
        cline)     setup_cline_smart ;;
        copilot)   setup_copilot_smart ;;
        windsurf)  setup_windsurf_smart ;;
        agents-md) setup_agents_md_smart ;;
        all)       setup_all ;;
        workspace) setup_workspace ;;
        *)         err "Unknown target: $target"; usage; exit 1 ;;
    esac
    echo ""
done

echo -e "${GREEN}Done.${NC}"
